src/views/games.py
from flask import (
    Blueprint,
    redirect,
    render_template,
    session,
    url_for,
)
from flask_socketio import emit, join_room

from src.extensions import db, socketio
from src.models import Game
from src.utils.decorators import *

games = Blueprint("games", __name__)


@games.route("/create/", methods=["POST"])
def create():
    new_game = Game()
    db.session.add(new_game)
    db.session.commit()
    return redirect(url_for("games.view", game_id=new_game.id))


@games.route("/<uuid:game_id>/")
@game_exists
@game_not_full
@login_required
def view(game_id, *, game, user):
    """
    Handle the view logic for a game based on how many players are currently in the game.

    :param game_id: UUID of the game passed in from the route
    :param game: Game object provided by the @game_exists decorator.
                 Represents the game corresponding to game_id.
    :param user: User object provided by the @login_required decorator.
                 Represents the currently logged-in user.
    """
    if game.contains_player(user.id):
        if game.is_full():
            return render_template("game_view.html")
        else:
            return render_template("waiting_room.html", username=user.username)

    game.add_player(user.id)

    if game.is_full():
        game.randomize_players()
        db.session.commit()

        socketio.emit("start", to=str(game_id))
        return render_template("game_view.html")
    else:
        db.session.commit()
        return render_template("waiting_room.html", username=user.username)


@games.route("/")
def list():
    """
    For development purposes only.
    """
    games = Game.query.all()
    output = "<html><body>"
    for game in games:
        game_link = url_for("games.view", game_id=game.id, _external=True)
        output += f"<input type='text' value='{game_link}' id='game_{game.id}'>"
        output += f"<button onclick=\"copyToClipboard('game_{game.id}')\">Copy</button><br>"
    output += """
        <script>
        function copyToClipboard(elementId) {
            var copyText = document.getElementById(elementId);
            copyText.select();
            document.execCommand('copy');
        }
        </script>
        </body></html>"""

    return output


@socketio.on("join")
@socket_room_required
@socket_game_exists
def join(data, *, room, game):
    """
    Handle join events sent from the client and broadcast them to all users in the room.

    :param data: Dictionary containing the room to send the message to.
    :param room: UUID of the room provided by the @socket_room_required decorator.
    """
    join_room(room)

    user_id = session.get("user_id")
    invert = (user_id == game.black_player_id)  # Only invert for black player
    ended = game.is_ended

    emit("joined", {"pgn": game.pgn(), "invert": invert, "ended": ended})


@socketio.on("move made")
@socket_login_required
@socket_room_required
@socket_game_exists
def move_made(data, *, user, room, game):
    """
    Handle move made events sent from the client and broadcast them to all users in the room.

    :param data: Dictionary containing the move to be made and the room to send the message to.
    :param user: User object provided by the @socket_login_required decorator.
    :param room: UUID of the room provided by the @socket_room_required decorator.
    :param game: Game object provided by the @socket_game_exists decorator.
    """
    move = data.get("move")
    if not move:
        emit("message", {"message": "Invalid data"})
        return

    if not game.contains_player(user.id):
        emit("error", {"message": "You are not in this game"})
        return

    if not game.is_turn(user.id):
        emit("error", {"message": "Not your turn"})
        return

    # if it is current player's turn, check to see if they are in checkmate

    # CURRENTLY NOT WORKING NOT SURE WHY

    # if game.in_checkmate():
    #     if user_id == game.black_player_id:
    #         emit("victory", {"white": True})
    #     else:
    #         emit("victory", {"white": False})

    game.make_move(move)
    db.session.commit()

    emit("move made", {"move": move}, to=room)


@socketio.on("chat")
@socket_login_required
@socket_room_required
@socket_game_exists
def chat(data, *, user, room, game):
    """
    Handle chat messages sent from the client and broadcast them to all users in the room.

    :param data: Dictionary containing the message and room to send the message to.
    :param user: User object provided by the @socket_login_required decorator.
    :param room: UUID of the room provided by the @socket_room_required decorator.
    :param game: Game object provided by the @socket_game_exists decorator.
    """
    message = data.get("message")
    if game.contains_player(user.id):
        emit("chat", {"username": user.username, "message": message}, to=room)


@socketio.on("draw")
@socket_login_required
@socket_room_required
@socket_game_exists
def draw(data, *, user, room, game):
    """
    Handle draw requests sent from the client and broadcast them to all users in the room.

    :param data: Dictionary containing the room to send the message to.
    :param user: User object provided by the @socket_login_required decorator.
    :param room: UUID of the room provided by the @socket_room_required decorator.
    :param game: Game object provided by the @socket_game_exists decorator.
    """
    if not game.contains_player(user.id):
        emit("error", {"message": "You are not in this game"})
        return

    game.is_ended = True
    db.session.commit()
    emit("draw", to=room)


@socketio.on("resign")
@socket_login_required
@socket_room_required
@socket_game_exists
def resign(data, *, user, room, game):
    """
    Handle resign requests sent from the client and broadcast them to all users in the room.

    :param data: Dictionary containing the room to send the message to.
    :param user: User object provided by the @socket_login_required decorator.
    :param room: UUID of the room provided by the @socket_room_required decorator.
    :param game: Game object provided by the @socket_game_exists decorator.
    """
    if not game.contains_player(user.id):
        emit("error", {"message": "You are not in this game"})
        return

    game.is_ended = True
    db.session.commit()
    winner = "white" if user.id == game.black_player_id else "black"
    emit("victory", {"winner": winner}, to=room)

src/views/users.py
from flask import (
    Blueprint,
    session,
    request,
    url_for,
    render_template,
    redirect,
)

from src.extensions import db
from src.models import User

users = Blueprint("users", __name__)


@users.route("/create/", methods=["GET", "POST"])
def create():
    if not session.get("url"):
        session["url"] = request.args.get("prev") or url_for("index", _external=True)

    if request.method == "POST":
        username = request.form.get("username")
        if not username:
            return render_template("user_create.html")

        new_user = User(username=username)
        db.session.add(new_user)
        db.session.commit()
        session["user_id"] = new_user.id

        # Redirect to the page the user was on before logging in
        return redirect(session.pop("url"))

    return render_template("user_create.html")


# TODO: Delete this route before deploying
@users.route("/")
def list_all():
    users = User.query.all()
    output = "<html><body>"
    for user in users:
        output += f"<p>{user.username}</p>"
    output += "</body></html>"

    return output

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
        {% filter indent(width=8) %}
        {% block styles %}
        {% endblock %}
        {% endfilter %}
        <title>{% block title %}Chess with Friends{% endblock %}</title>
    </head>
    <body>
        <div class="container">
            <div class="message" id="info"></div>
            <div class="message" id="warning"></div>
            <div class="message" id="error"></div>
            <h1><a href="{{ url_for('index') }}">Chess</a></h1>
            {% filter indent(width=12) %}
            {% block content %}
            {% endblock %}
            {% endfilter %}
        </div>
        <script crossorigin="anonymous"
                integrity="sha384-mZLF4UVrpi/QTWPA7BjNPEnkIfRFn4ZEO3Qt/HFklTJBj/gBOV8G3HcKn4NfQblz"
                src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
        <script src="{{ url_for('static', filename='dist/base.bundle.js') }}"></script>
        {% filter indent(width=8) %}
        {% block scripts %}
        {% endblock %}
        {% endfilter %}
    </body>
</html>

src/templates/game_view.html
{% extends 'base.html' %}

{% block styles %}
<link href="{{ url_for('static', filename='css/chessboard-1.0.0.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/game_view.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="game-view-container">
    <div id="board"></div>
    <div class="game-interaction-section">
        <div class="move-history-wrapper">
            <table>
                <thead>
                <tr>
                    <th>Move</th>
                    <th>White</th>
                    <th>Black</th>
                </tr>
                </thead>
                <tbody>
                <!-- Move history will be listed here -->
                </tbody>
            </table>
        </div>
        <div class="game-actions">
            <button id="resign">Resign</button>
            <button id="draw">Offer Draw</button>
        </div>
        <ul id="chatMessage">
            <!-- Chat messages will be listed here -->
        </ul>
        <input id="message" placeholder="Send a message!" type="text">
    </div>
    <div class="modal" id="modal">
        <div class="modal-header">
            <div class="title">Game has finished</div>
            <button class="close-button" data-close-button>&times;</button>
        </div>

        <!-- pop up details when win -->
        <div class="modal-body">
            <div class="modal-text"></div>
            <button id="rematch">Yes</button>
            <!-- Ideally this should just be an <a> tag that should look like a button using css -->
            <button><a href="{{ url_for('index') }}">No</a></button>
        </div>
    </div>

    <div id="overlay"></div>
</div>
{% endblock %}

{% block scripts %}
<script crossorigin="anonymous"
        integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"
        src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>var pieceThemePath = "{{ url_for('static', filename='img/chesspieces/wikipedia/') }}{piece}.png"</script>
<script src="{{ url_for('static', filename='js/chessboard-1.0.0.min.js') }}"></script>
<script crossorigin="anonymous"
        integrity="sha384-mZLF4UVrpi/QTWPA7BjNPEnkIfRFn4ZEO3Qt/HFklTJBj/gBOV8G3HcKn4NfQblz"
        src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
<script src="{{ url_for('static', filename='dist/game_view/main.bundle.js') }}"></script>
<script src="{{ url_for('static', filename='dist/game_view/board.bundle.js') }}"></script>
<script src="{{ url_for('static', filename='dist/game_view/chat.bundle.js') }}"></script>
<script src="{{ url_for('static', filename='dist/game_view/modal.bundle.js') }}"></script>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block content %}
    <div class="index-container">
        <form action="{{ url_for('games.create') }}" method="POST">
            <input type="submit" value="Play against a friend">
        </form>
        <a href="{{ url_for('todo') }}">
            Play against the computer
        </a>
    </div>
{% endblock %}

src/templates/todo.html
{% extends 'base.html' %}

{% block content %}
    <h1>WIP</h1>
{% endblock %}

src/templates/user_create.html
{% extends 'base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user_create.css') }}">
{% endblock %}

{% block content %}
    <div class="user-create-container">
        <h2 class="form-header">Choose your username</h2>
        <form action="{{ url_for('users.create') }}" method="post">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" required>
            <input type="submit" value="Join">
        </form>
    </div>
{% endblock %}

src/templates/waiting_room.html
{% extends "base.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/waiting_room.css') }}">
{% endblock %}

{% block content %}
    <div class="header">Waiting for players</div>
    <p>Hey {{ username }}, share this link with your friend to start the game:</p>
    <div class="input-group">
        <input type="text" value="{{ request.url }}" id="gameLink" readonly>
        <button onclick="copyToClipboard('gameLink')">
            <svg xmlns="http://www.w3.org/2000/svg" height="24" width="21" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M208 0H332.1c12.7 0 24.9 5.1 33.9 14.1l67.9 67.9c9 9 14.1 21.2 14.1 33.9V336c0 26.5-21.5 48-48 48H208c-26.5 0-48-21.5-48-48V48c0-26.5 21.5-48 48-48zM48 128h80v64H64V448H256V416h64v48c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V176c0-26.5 21.5-48 48-48z"/></svg>
        </button>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.socket.io/4.7.2/socket.io.min.js" integrity="sha384-mZLF4UVrpi/QTWPA7BjNPEnkIfRFn4ZEO3Qt/HFklTJBj/gBOV8G3HcKn4NfQblz" crossorigin="anonymous"></script>
    <script src={{ url_for('static', filename='dist/waiting_room.bundle.js') }}></script>
    <script type="text/javascript">
        function copyToClipboard(elementId) {
            var copyText = document.getElementById(elementId);
            copyText.select();
            document.execCommand("copy");
        }
    </script>
{% endblock %}